name: Make release assets

on:
  release:
    types:
      - created

jobs:
  make-assets:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Upload assets
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./xssh
          asset_name: xssh
          asset_content_type: application/x-sh
